### ISSUE TITLE
Difficulty in Replicating Reported Results Using Provided Model Weights

### ISSUE THREAD

**Issue by Romantic1412** [Doubiiu/AIDN#1]
Thanks for your exciting work.

I have been attempting to reproduce the results reported in your paper using the provided model weights `AIDN.pth.tar`. However, despite following the test function in `benchmark.py`, I have been unable to achieve the same level of performance as stated in the publication.

Furthermore, I noticed a significant discrepancy when comparing the results obtained using the provided model weights with those achieved using the bicubic sampling method. Could you kindly provide guidance on whether there are any specific details or nuances that should be taken into consideration to ensure the successful replication of the reported results? 

Thank you very much for your attention and assistance in resolving this issue.

**Comment by LiuXiYing** [comment]
I have the same problem , have you resolved it?

**Comment by Doubiiu** [comment]
@Romantic1412 @LiuXiYing Hi, I am double-checking the code and model weights and will fix the potential issue soon.

**Comment by Doubiiu** [comment]
@Romantic1412 @LiuXiYing Hi, I found `align_corners` in F.grid_sample() (i.e. L293 of [arb.py](https://github.com/Doubiiu/AIDN/blob/main/models/arb.py)) may have different default performances on various environments and devices, thus I fix it to `True` manually. Besides, I provide a small-scale dataset (`Set5`) for reproduction purpose, please check if the reproduction result is consistent with that in the paper. Sorry for the inconvenience caused and thanks for your interest in our paper.

**Comment by LiuXiYing** [comment]
@Doubiiu Thank you for addressing our problem. I experimented with a pre-trained model on the test dataset, and it yielded good results. Thanks for your efforts！
