### ISSUE TITLE
I encountered an error while trying to create a conda environment using the provided `AIDN.yml` file.

### ISSUE THREAD

**Issue by pranavkrishnayadav** [Doubiiu/AIDN#2]
**Steps to Reproduce:**

1. Clone the repository: [Repository Link](https://github.com/doubiiu/AIDN)
2. Navigate to the repository directory.
3. Run the following command:

conda env create -f AIDN.yml

**Expected Behavior:**

I expected the conda environment to be created successfully using the provided YAML file without any errors.

**Actual Behavior:**

The `conda env create` command failed with the following error:
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:

**Environment:**

- Operating System: [e.g., Windows 11]
- Python Version: [e.g., Python 3.10]
- Conda Version: [23.9]
**Reproducibility:**

The issue is consistently reproducible.

**Additional Information:**

I have attached a screenshot of the error message for reference.

<img width="658" alt="image" src="https://github.com/Doubiiu/AIDN/assets/126273877/c8122692-d14f-40d0-b6a2-e404d5d79d97">

**Repository/Branch:**

I encountered this issue on the main branch of the repository.

Thank you for your assistance in resolving this issue.

**Comment by Doubiiu** [comment]
Hi, I am sorry for the inconvenience caused. I have modified the environment setup steps, so you can try to set up the environment from the beginning using the new guidelines.

**Comment by pranavkrishnayadav** [comment]
sh scripts/train.sh <exp_name> <config_path>
e.g.: sh scripts/train.sh AIDN_exp01 config/DIV2K/AIDN.yaml

please update this also as AIDN.yaml is not present in the project directory.

**Comment by Doubiiu** [comment]
Not actually. AIDN.yaml is still there: [config/DIV2K/AIDN.yaml](https://github.com/Doubiiu/AIDN/tree/main/config/DIV2K)

**Comment by pranavkrishnayadav** [comment]
i am unable the create the environment to run the model the dependencies in the requirement file is not installing. I want to test the model with different data sets. Requesting you to tell the steps to run the model.
I am getting following errors :
<img width="814" alt="image" src="https://github.com/Doubiiu/AIDN/assets/126273877/8a0f8a9b-538e-4328-9ef3-82bec295ef46">

<img width="756" alt="Screenshot 2023-10-11 140549" src="https://github.com/Doubiiu/AIDN/assets/126273877/a7a9ea61-401b-4a8b-a7f4-8068172881bd">


So requesting you to tell the steps to run the model and test it with different datasets

**Comment by Doubiiu** [comment]
please follow the instructions to create a python3.6 environment. I have tested the environment setup with no problem.

**Comment by pranavkrishnayadav** [comment]
Hello sir, I am working on this project for my research work, from last one month ,where i want test the model which different medical data sets.  So, i have installed and created all the environments in my windows 11  but coming to this command

   sh scripts/AIDN_benchmark.sh config/DIV2K/AIDN_benchmark.yaml

we can only run only in Linux environment . But i am not familiar with linux /Ubuntu  and also again from scratch i need to install al the modules and need to create environment which become difficult and also less time avaliable to me.

so requesting you to help me how to run this in windows 11.
        Thanking you

**Comment by Doubiiu** [comment]
Hi I think there is no much difference between installing the required environment on Linux and Windows platform. What is your error message when setting up the environement on Windows?

**Comment by pranavkrishnayadav** [comment]
there no error  while setting up environment in windows. But the problem is, while testing the model(set 5 Dataset which is provided] ,how to run the below  benchmarking script in windows command prompt as 'sh' command is shell script language, which can run only on linux . So  requesting you to provide  benchmarking script  that can be run on  windows command prompt/vs code.

sh scripts/AIDN_benchmark.sh config/DIV2K/AIDN_benchmark.yaml

**Comment by Doubiiu** [comment]
You can have a look at the shell file `AIDN_benchmark.sh`, it just creates directories(you can create those manually), sets the PYTHON path(setset PYTHONPATH=%PYTHONPATH%; .\) and run the python script (python xxxxx). You can do that mannally in Windows, while I cannot support you with Windows environment.

**Comment by Morayabb** [comment]
@pranavkrishnayadav Can you run this code in windows now?
