### ISSUE TITLE
pre-trained weights problem

### ISSUE THREAD

**Issue by Morayabb** [Doubiiu/AIDN#3]
Thanks for your excellent work!!
When I tried to run the experiment in the order in the readme file, I did not find a downloadable pre-training weight file, where can I download this? thank you.

**Comment by Doubiiu** [comment]
Hi. All links to the pre-trained weights are listed in the README, "Benchmark the pre-trained model weights" section.

**Comment by Morayabb** [comment]
Ok, maybe I can't jump to the download interface because of my network problem. Thank you for your reply. Thank you.

**Comment by Morayabb** [comment]
Hello, I have solved the above problem. If it is convenient, could you please provide the screenshot of the interface when the code is running? So I can compare it with my running process, thank you.
