### ISSUE TITLE
 DIV2K Preparation

### ISSUE THREAD

**Issue by zhangdan8962** [Doubiiu/AIDN#4]
Hi,

I am wondering why we have to crop original images to patches rather than directly using them? Also, why you further crop the input from 480px to 192px. The whole data pre-processing is kind of confusing. Could you please provide some explanation?

**Comment by Doubiiu** [comment]
Hi. 
1. We preprocess the original data by patchifing the images for better I/O.
2. We randomly crop the loaded images to 192x192 as a data augmentation method, which can also reduce the burden due to limited GPU memory.

**Comment by zhangdan8962** [comment]
> Hi.
> 
> 1. We preprocess the original data by patchifing the images for better I/O.
> 2. We randomly crop the loaded images to 192x192 as a data augmentation method, which can also reduce the burden due to limited GPU memory.

So when you evaluate the model, the input would also be 192x192 patches?

**Comment by Doubiiu** [comment]
No, for evaluation, we directly use the original size of those images in the datasets.

**Comment by zhangdan8962** [comment]
For original size, do you mean 2K resolution or 480x480?

**Comment by Doubiiu** [comment]
2K.

**Comment by zhangdan8962** [comment]
Got it. And I have another question. Since the original image size in DIV2K_VAL is different from image to another, how do you handle such situation during evaluation?

**Comment by Doubiiu** [comment]
Hi. But I didn't see any problems here? Just take the images with arbitrary resolutions and set batchsize=1.

**Comment by zhangdan8962** [comment]
Thank you for the reply. I was wondering if you were using batchsize of 1 and now it makes sense.
